version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'moneyfx'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - main

  payments:
    build:
      context: ./rest_django_payments
      dockerfile: Dockerfile
    volumes:
      - ./rest_django_payments:/manning/rest_django_payments
    ports:
      - "8200:8200"
    depends_on:
      - postgresql
    networks:
      - main

  trading:
    build:
      context: ./rest_django_trading
      dockerfile: Dockerfile
    volumes:
      - ./rest_django_trading:/manning/rest_django_trading
    ports:
      - "8100:8100"
    depends_on:
      - postgresql
    networks:
      - main

networks:
  main:
